### ISSUE TITLE
Ummm...

### ISSUE THREAD

**Issue by PaigeDDLC** [instilledbee/DDLC-PoemGen#2]
Okay so I'm not sure if this was supposed to happen or not but when I downloaded my poem what actually saved was a creepy af picture of Monika. Sorry if this was supposed to happen it just kind of startled me when I saw that instead of my poem.

**Comment by instilledbee** [comment]
There is a small chance Monika will attempt to show you she is more important than your own poems...

(Seriously speaking, yes, this is one of the easter eggs in the poem generator. Feel free to try downloading again, it's just a small random chance it'll replace your download with that image.)

**Comment by PaigeDDLC** [comment]
Okay, thanks! I pretty much figured.
