### ISSUE TITLE
Download button doesn't preserve new lines

### ISSUE THREAD

**Issue by LoveShakeDev** [instilledbee/DDLC-PoemGen#3]
Browser: Firefox 119.0

STR:
Make a poem with the following text:

```
test
test
test
```

Hit the download button, and the result will be like the following (depending on chosen author)
![poem(3)](https://github.com/instilledbee/DDLC-PoemGen/assets/121775581/3ab01f24-0841-4b82-ba3a-9ec363d49e80)

**Comment by instilledbee** [comment]
Thanks for reporting. I'll look into this week.

**Comment by instilledbee** [comment]
Hey @CooperMidnight, sorry for taking a while to fix this. Should be fixed in the latest version of the webpage. Let me know if you run into any more issues. Thanks!
